### ISSUE TITLE
Question: Power consumption?

### ISSUE THREAD

**Issue by MichaelVoelkel** [eitherway/lollidisplay#1]
Hi,

do you run it from battery or a power outlet? How is the power consumption of the whole setup? Sounds indeed like a very nice project!

**Comment by eitherway** [comment]
Hi, 
currently this project runs from the power outlet.
 I also don't have the set up to measure the power consumption ( currently)

**Comment by MichaelVoelkel** [comment]
Thanks for the prompt answer!
